server:
  port: 8010

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka,http://127.0.0.1:8001/eureka,http://127.0.0.1:8002/eureka

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wusihualogk/blog-config-file
          username: wusihualogk
          password: wms8513245246
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
#management:
#  security:
#    enabled: false

#management:
#  endpoint:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh
#  本地配置文件配置方式
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config


